dist: bionic
language: go
go:
  - 1.13.x
  - master
  - tip
os:
  - linux
  - osx
jobs:
  allow_failures:
    - go: tip
  fast_finish: true
  include:
    - stage: deploy
      name: Publish release
      os: linux
      go: master
      deploy:
        provider: releases
        api_key:
          secure: T8OdCbs9olMN5jD/GSgY+ZC3lghnniICp3PWk5YtCzwsUhY92cFz6LfPszrmkrXxyldCAgjxmH33m1Dbfa9KfDiM0dtHXv2VlnMTD5ll9YnGFGo4raU7fI47PknS5lUbZu6k/LsiOlqV43NJpK9FTJuk/FMftlJjuF/hbneCqffWPQQTti/NCJ8SypCKOWyw5ZMwRYql8FkS8abkVUuQWYYbTow+TSGo6Wwy0F3ewrqasAhA+2kSvmYu2Vii8R+tcDE3c8nHpFtxjiqWiPsv79mhbJlUD/8szeoiqYYdeNYagwpT9/2CC8qJLv0k64KEfwGw+pDwZsW/St+iJonjjvEIdE4Fq5UHdqlNdN9fWEe5GtVzWNWm3g013gd8VbGBdGKHDC7AZgOXLJL0IaFz9n3F5nVkTGWAdq3eKyHZyay2vDMX8RLwZiJEP47htXGwmDYZ+pAnEe3N07jpzjOGJ3JAiig4UTP2m7G6zgTlRR70fNwtv7a/mNpOvu6hRSEVSJZE5bf5Lg4c9cCXCei4gK1mTpqV4W2wZhkQIf/YNAnbB9l3yTibXUZIW50wruLhrcySYu2JII4U+vGTNH+lde8CZ6y01XLHOuO+nji9+gSpJouLdI808x31LrSkV9mG3knklGYfYM5c6Xah17qFblWMSeg8xkBzkbzuQyAcLEA=
        file: mongoimport
        skip_cleanup: true
        on:
          tags: true
install: true
notifications:
  email: false
before_script:
  - go get -u golang.org/x/lint/golint
  - go get github.com/fzipp/gocyclo
script:
  - pip install -U pip && pip install pre-commit && pre-commit run --all-files
  - env GO111MODULE=on go build -o mongoimport github.com/romnnn/mongoimport/cmd/mongoimport
  - env GO111MODULE=on go test -v -race -coverprofile=coverage.txt -covermode=atomic github.com/romnnn/mongoimport/validation

after_success:
  - bash <(curl -s https://codecov.io/bash)
